version: '3.8'
services:
  server:
    image: node:18-alpine
    container_name: cashflowr-server
    restart: always
    command: npm run dev
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "3300:3300"
    depends_on:
      - database

  database:
    image: mongo:6
    container_name: cashflowr-database
    restart: always
    ports:
      - "27017:27017"